# Generated by Django 5.0.6 on 2024-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deadline_status',
            field=models.BooleanField(default=False),
        ),
    ]
