# Generated by Django 4.2 on 2024-05-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtasks',
            options={'verbose_name_plural': 'SubTasks'},
        ),
        migrations.RenameField(
            model_name='subtasks',
            old_name='task_name',
            new_name='subtask_name',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtasks',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='kanban.tasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
